입력->중간층->중간층->출력 노드의 수가 2 -> 3 -> 2 -> 1 인 네트워크를 만듭니다.

In [1]:
# 2 -> 3 -> 2 -> 1

import tensorflow.keras as keras
import numpy as np

x_train = np.array( [[0,1], [2,3], [4,5]] )
y_train = np.array( [ [x.sum()] for x in x_train ] )
print("x_train ="); print(x_train)
print("y_train ="); print(y_train)
x_test = np.array( [[6,7], [8,9]] )
y_test = np.array( [ [x.sum()] for x in x_test ] )
print("x_test ="); print(x_test)
print("y_test ="); print(y_test)

model = keras.models.Sequential()
model.add( keras.layers.Dense( 3, input_dim=2 ) )
model.add( keras.layers.Dense( 2 ) )
model.add( keras.layers.Dense( 1 ) )

model.summary()

model.compile( optimizer = 'SGD', loss = 'mse' )
model.fit( x_train, y_train, batch_size = 3, epochs = 1000, verbose = 0 )

y_predict = model.predict( x_test )
print( 'y_predict' ); print( y_predict )
print( 'y_test' ); print( y_test )

x_train =
[[0 1]
 [2 3]
 [4 5]]
y_train =
[[1]
 [5]
 [9]]
x_test =
[[6 7]
 [8 9]]
y_test =
[[13]
 [17]]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 9         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
y_predict
[[13.000183]
 [17.000238]]
y_test
[[13]
 [17]]
