입력->중간층->출력 의 노드 갯수가 1 -> 2 -> 1 인 모델을 함수형 API 를 사용해서 만듭니다.

In [1]:
# 1 -> 2 -> 1

import tensorflow.keras as keras
import numpy as np

x_train = np.array( [[0],[1]] )
y_train = x_train * 2 + 1
print('x_train'); print(x_train)
print('y_train'); print(y_train)
x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test'); print(x_test)
print('y_test'); print(y_test)

x = keras.layers.Input( shape=(1,) )
h = keras.layers.Dense(2)(x)
y = keras.layers.Dense(1)(h)

model = keras.models.Model(x,y)
model.summary()

model.compile( optimizer = 'SGD', loss = 'mse' )
model.fit( x_train, y_train, batch_size=2, epochs=1000, verbose=0 )

y_predict = model.predict( x_test )
print( 'y_predict' ); print( y_predict )
print( 'y_test' ); print( y_test )

x_train
[[0]
 [1]]
y_train
[[1]
 [3]]
x_test
[[2]
 [3]]
y_test
[[5]
 [7]]
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 4         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________
y_predict
[[4.9999914]
 [6.9999857]]
y_test
[[5]
 [7]]
