학습 데이터와 테스트 데이터를 정의합니다.

In [1]:
# 2 -> 3 -> 2 -> 1

import tensorflow.keras as keras
import numpy as np

x_train = np.array( [[0,1], [2,3], [4,5]] )
y_train = np.array( [ [x.sum()] for x in x_train ] )
x_test = np.array( [[6,7], [8,9]] )
y_test = np.array( [ [x.sum()] for x in x_test ] )

전체 모델과 중간 모델을 만듭니다.

In [2]:
x  = keras.layers.Input(shape=(2,), name='x' )
h1 = keras.layers.Dense(3, name='h1')(x)
h2 = keras.layers.Dense(2, name='h2')(h1)
y  = keras.layers.Dense(1, name='y' )(h2)

model_h1 = keras.models.Model(x, h1)
model_h2 = keras.models.Model(x, h2)
model = keras.models.Model(x, y)

model_h1.summary()
model_h2.summary()
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               [(None, 2)]               0         
_________________________________________________________________
h1 (Dense)                   (None, 3)                 9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               [(None, 2)]               0         
_________________________________________________________________
h1 (Dense)                   (None, 3)                 9         
_________________________________________________________________
h2 (Dense)                   (None, 2)                 8         
Total params: 17
Trainable params: 17
Non-trainabl

중간 층의 출력을 확인합니다.

In [3]:
model.compile( 'SGD', 'mse' )
model.fit( x_train, y_train, batch_size = 3, epochs = 1000, verbose = 0 )

print( 'h1' ); print( model_h1.predict(x_test) )
print( 'h2' ); print( model_h2.predict(x_test) )
print( 'y' ); print( model.predict(x_test) )

h1
[[ 8.172809  -3.4071772  5.59763  ]
 [10.623313  -4.4594703  7.225649 ]]
h2
[[ -6.810478   -9.171081 ]
 [ -8.8319845 -11.981508 ]]
y
[[12.999894]
 [16.999863]]


이름으로 중간 층을 가지고 옵니다.

In [4]:
layer_h1 = model.get_layer('h1')
layer_h2 = model.get_layer('h2')
model_h1 = keras.models.Model(model.input, layer_h1.output)
model_h2 = keras.models.Model(model.input, layer_h2.output)
print( 'h1' ); print( model_h1.predict(x_test) )
print( 'h2' ); print( model_h2.predict(x_test) )
print( 'y' ); print( model.predict(x_test) )

h1
[[ 8.172809  -3.4071772  5.59763  ]
 [10.623313  -4.4594703  7.225649 ]]
h2
[[ -6.810478   -9.171081 ]
 [ -8.8319845 -11.981508 ]]
y
[[12.999894]
 [16.999863]]


인덱스로 중간 층을 가지고 옵니다.

In [5]:
layer_h1 = model.get_layer(index=1)
layer_h2 = model.get_layer(index=2)
model_h1 = keras.models.Model(model.input, layer_h1.output)
model_h2 = keras.models.Model(model.input, layer_h2.output)
print( 'h1' ); print( model_h1.predict(x_test) )
print( 'h2' ); print( model_h2.predict(x_test) )
print( 'y' ); print( model.predict(x_test) )

h1
[[ 8.172809  -3.4071772  5.59763  ]
 [10.623313  -4.4594703  7.225649 ]]
h2
[[ -6.810478   -9.171081 ]
 [ -8.8319845 -11.981508 ]]
y
[[12.999894]
 [16.999863]]
