모델의 중간층의 출력을 볼수 있는 방법을 알아보겠습니다. 먼저 학습 데이터와 테스트 데이터를 정의합니다.

In [1]:
# 1 -> 2 -> 1

import tensorflow.keras as keras
import numpy as np

x_train = np.array( [[0],[1]] )
y_train = x_train * 2 + 1
print('x_train'); print(x_train)
print('y_train'); print(y_train)
x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test'); print(x_test)
print('y_test'); print(y_test)

x_train
[[0]
 [1]]
y_train
[[1]
 [3]]
x_test
[[2]
 [3]]
y_test
[[5]
 [7]]


모델을 만들고 학습시킵니다. 이번에는 출력층에 이름까지 넣어줍니다.

In [2]:
x = keras.layers.Input( shape=(1,), name='x' )
h = keras.layers.Dense( 2, name='h' )(x)
y = keras.layers.Dense( 1, name='y' )(h)
model = keras.models.Model(x,y)
model.summary()

model.compile( 'SGD', 'mse' )
history = model.fit( x_train, y_train, batch_size=2, epochs=1000, verbose=0 )

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               [(None, 1)]               0         
_________________________________________________________________
h (Dense)                    (None, 2)                 4         
_________________________________________________________________
y (Dense)                    (None, 1)                 3         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________


다음과 같이 중간층의 출력을 볼 수 있는 모델을 만들어 확인할 수 있습니다. 이 예제에서는 모델을 학습한 후 중간 모델을 정의 했지만 모델을 학습하기 전에 정의해도 됩니다.

In [3]:
model_h = keras.models.Model(x,h)
model_h.summary()

print( 'h' ); print( model_h.predict( x_test ) )
print( 'y' ); print( model.predict( x_test ) )

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               [(None, 1)]               0         
_________________________________________________________________
h (Dense)                    (None, 2)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
h
[[1.0329008 3.5059717]
 [1.5206254 5.176655 ]]
y
[[4.999988]
 [6.999979]]


혹은 다음과 같이 이름으로 레이어를 가지고 와서 중간 모델을 정의하고 확인할 수 있습니다.

In [4]:
layer_h = model.get_layer('h')
model_h = keras.models.Model(model.input, layer_h.output)

print( 'h' ); print( model_h.predict( x_test ) )
print( 'y' ); print( model.predict( x_test ) )

h
[[1.0329008 3.5059717]
 [1.5206254 5.176655 ]]
y
[[4.999988]
 [6.999979]]


혹은 다음과 같이 인덱스로 레이어를 가지고 올 수 있습니다.

In [5]:
layer_h = model.get_layer(index=1)
model_h = keras.models.Model(model.input, layer_h.output)

print( 'h' ); print( model_h.predict( x_test ) )
print( 'y' ); print( model.predict( x_test ) )

h
[[1.0329008 3.5059717]
 [1.5206254 5.176655 ]]
y
[[4.999988]
 [6.999979]]
