activation 함수들을 backend.exp 와 backend.switch 함수를 사용하여 Lambda layer 로 대체해보겠습니다

In [1]:
from tensorflow.keras import layers, models
import tensorflow.keras.backend as K
import numpy as np

x_test = np.array([[-1],[2]])
x = layers.Input((1,))

sigmoid 함수를 Lambda layer 로 대체해 보겠습니다.

In [2]:
y = layers.Activation('sigmoid')(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

y = layers.Lambda(lambda x: 1/(1+K.exp(-x)))(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[0.26894143]
 [0.880797  ]]
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda (Lambda)              (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[0.26894143]

tanh 함수를 Lambda layer 로 대체해 보겠습니다.

In [3]:
y = layers.Activation('tanh')(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

y = layers.Lambda(lambda x: (1-K.exp(-2*x))/(1+K.exp(-2*x)))(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[-0.7615942]
 [ 0.9640276]]
Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[-0.761594

relu 함수를 Lambda layer 로 대체해 보겠습니다.

In [4]:
y = layers.Activation('relu')(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

y = layers.Lambda(lambda x: K.switch(x>0, x, K.zeros_like(x)))(x)
model = models.Model(x,y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[0.]
 [2.]]
Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
lambda_2 (Lambda)            (None, None)              0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred
[[0.]
 [2.]]
