여러개의 입력을 하나로 합치는 layer 에 대해서 알아봅시다.

In [1]:
from tensorflow.keras import layers, models
import numpy as np

x_test_A = np.array([[0,1],[4,5]])
x_test_B = np.array([[2,3],[6,7]])

xA = layers.Input(shape=(2,), name='xA')
xB = layers.Input(shape=(2,), name='xB')

입력을 그대로 이어서 붙이는 Concatenate 을 사용해 봅시다. 소문자로 시작하는 concatenate 은 괄호 안에 바로 입력 텐서를 넣어주면 됩니다.

In [2]:
y = layers.Concatenate(name='concat')([xA, xB])
#y = layers.concatenate([xA, xB], name='cancat')
model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
concat (Concatenate)            (None, 4)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B
[

입력을 더해서 하나로 만드는 Add

In [3]:
y = layers.Add(name='add')([xA, xB])
#y = layers.add([xA, xB], name='add')
model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
add (Add)                       (None, 2)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B

두 입력을 곱해서 하나로 만드는 Multiply

In [4]:
y = layers.Multiply(name='mul')([xA, xB])
#y = layers.multiply([xA, xB], name='mul')
model = models.Model(inputs=[xA, xB], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
xA (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
xB (InputLayer)                 [(None, 2)]          0                                            
__________________________________________________________________________________________________
mul (Multiply)                  (None, 2)            0           xA[0][0]                         
                                                                 xB[0][0]                         
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B