함수형 모델을 클래스로 만드는 방법을 알아보겠습니다. 먼저 데이터를 정의합니다.

In [1]:
from tensorflow.keras import layers, models
import numpy as np

x_train = np.array( [[0,1], [2,3], [4,5]] )
y_train = np.sum(x_train, axis=1, keepdims=True)
print('x_train'); print(x_train)
print('y_train'); print(y_train)
x_test = np.array( [[6,7], [8,9]] )
y_test = np.sum(x_test, axis=1, keepdims=True)
print('x_test'); print(x_test)
print('y_test'); print(y_test)

x_train
[[0 1]
 [2 3]
 [4 5]]
y_train
[[1]
 [5]
 [9]]
x_test
[[6 7]
 [8 9]]
y_test
[[13]
 [17]]


다음과 같이 함수형 모델에서 상속받아 중간 층이 하나인 모델을 클래스로 만들 수 있습니다. \_\_init\_\_ 함수에서 층들을 다 연결한 다음에 부모클래스의 \_\_init\_\_ 에 입력과 출력을 넣어주어 모델을 만듭니다.

In [2]:
class FuncFNN( models.Model ):
    def __init__(self, Ni, Nh, No):
        x = layers.Input((Ni,))
        h = layers.Dense(Nh)(x)
        y = layers.Dense(No)(h)
        super().__init__(x, y)
        self.compile( 'sgd', 'mse' )

다음과 같이 클래스로 정의한 모델을 사용합니다.

In [3]:
model = FuncFNN( 2, 3, 1 )
model.summary()
model.fit( x_train, y_train, batch_size = 3, epochs = 1000, verbose = 0 )

y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)
print('y_test'); print(y_test)

Model: "func_fnn"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense (Dense)                (None, 3)                 9         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 4         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________
y_pred
[[13.]
 [17.]]
y_test
[[13]
 [17]]
