모델의 구조와 학습한 웨이트들을 저장하고 다시 불러오는 방법에 대해 알아보겠습니다. 일단 아래와 같이 모델을 만들고 학습시킵니다.

In [1]:
from tensorflow.keras import layers, models
import numpy as np

x_train = np.array( [[0,1], [2,3], [4,5]] )
y_train = np.sum(x_train, axis=1, keepdims=True)
print('x_train'); print(x_train)
print('y_train'); print(y_train)
x_test = np.array( [[6,7], [8,9]] )
y_test = np.sum(x_test, axis=1, keepdims=True)
print('x_test'); print(x_test)
print('y_test'); print(y_test)

x = layers.Input((2,))
h = layers.Dense(3)(x)
h = layers.Dense(2)(h)
y = layers.Dense(1)(h)

model = models.Model(x, y)
model.summary()

model.compile( 'sgd', 'mse' )
model.fit( x_train, y_train, batch_size = 3, epochs = 1000, verbose = 0 )

y_pred = model.predict(x_test)
print('y_pred'); print(y_pred)
print('y_test'); print(y_test)

x_train
[[0 1]
 [2 3]
 [4 5]]
y_train
[[1]
 [5]
 [9]]
x_test
[[6 7]
 [8 9]]
y_test
[[13]
 [17]]
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense (Dense)                (None, 3)                 9         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
y_pred
[[13.000144]
 [17.000187]]
y_test
[[13]
 [17]]


다음과 같이 학습된 모델의 구조와 웨이트들을 하나의 파일로 저장할 수 있습니다.

In [2]:
model.save('my_model.h5')

저장된 모델은 다음과 같이 읽어올 수 있습니다.

In [3]:
model = models.load_model('my_model.h5')
print( model.predict( x_test ) )
print( y_test )

[[13.000144]
 [17.000187]]
[[13]
 [17]]


다음과 같이 모델의 구조와 웨이트를 각각 저장할 수 있습니다.

다음과 같이 모델의 구조를 json 파일의 형태로 저장할 수 있습니다.

In [4]:
with open('my_model.json', 'w') as f:
    f.write(model.to_json())

다음과 같이 모델의 웨이트들을 저장할 수 있습니다.

In [5]:
model.save_weights('my_model_weights.h5')

다음과 같이 json 형태로 저장된 모델의 구조를 읽어 모델을 만들 수 있습니다.

In [6]:
with open('my_model.json', 'r') as f:
    json_string = f.read()

print(json_string)
model = models.model_from_json(json_string)
model.summary()

{"class_name": "Model", "config": {"name": "model", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 2], "dtype": "float32", "sparse": false, "ragged": false, "name": "input_1"}, "name": "input_1", "inbound_nodes": []}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 3, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "name": "dense", "inbound_nodes": [[["input_1", 0, 0, {}]]]}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 2, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Ze

다윽과 같이 모델의 웨이트들을 읽어올 수 있습니다.

In [7]:
model.load_weights('my_model_weights.h5')

print( model.predict( x_test ) )
print( y_test )

[[13.000144]
 [17.000187]]
[[13]
 [17]]
